services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
  db:
    ports:
      - "5432:5432"
    image: postgres:15
    environment:
      POSTGRES_USER: meetmate
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meetmate
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
