"""Add summary column to Recording

Revision ID: a22f243b3a2c
Revises: 
Create Date: 2025-05-09 15:51:10.528171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a22f243b3a2c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('transcript_path', sa.String(), nullable=True))
    op.add_column('recordings', sa.Column('summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recordings', 'summary')
    op.drop_column('recordings', 'transcript_path')
    # ### end Alembic commands ###
